slader_clone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from textbooks import views
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^textbooks/', include('textbooks.urls')),
    url(r'^admin/', admin.site.urls),
]

textbooks/urls.py
from django.conf.urls import url
from . import views

app_name = 'textbooks'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'about', views.about, name='about'),

    # ex: /polls/5/
    url(r'^(?P<isbn>[0-9]+)/$', views.textbook_detail, name='textbook_detail'),

    url(r'^(?P<isbn>[0-9]+)/new/$', views.new_exercise, name='new_exercise'),

    url(r'^(?P<isbn>[0-9]+)/page/(?P<page_number>[0-9]+)/$', views.page_detail, name='page_detail'),
]

textbooks/models.py
from django.db import models
from django.contrib.auth.models import User


# Textbook == Board
class Textbook(models.Model):
    isbn = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    date_published = models.DateField()
    description = models.CharField(max_length=200, blank=True)
    photo_url = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title


# Exercise == Topic
class Exercise(models.Model):
    page_number = models.IntegerField()
    exercise_number = models.CharField(max_length=4)
    last_updated = models.DateTimeField(auto_now_add=True)
    # Relational
    textbook = models.ForeignKey(Textbook, related_name='exercises')
    starter = models.ForeignKey(User, related_name='exercises')


# Solution == Post
class Solution(models.Model):
    final_answer = models.TextField()
    work_steps = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    # Relational
    exercise = models.ForeignKey(Exercise, related_name='solutions')
    created_by = models.ForeignKey(User, related_name='solutions')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

slader_clone/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'index.html')

textbooks/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from .models import Textbook, Exercise, Solution


# Show all textbooks in the database
def index(request):
    textbooks = Textbook.objects.all()
    return render(request, 'textbooks/index.html', {'textbooks': textbooks})


# Show a single textbook by ISBN
def textbook_detail(request, isbn):
    textbook = get_object_or_404(Textbook, isbn=isbn)
    return render(request, 'textbooks/textbook_detail.html', {'textbook': textbook})


# A static "About Me" page
def about(request):
    return render(request, 'textbooks/about.html')


def new_exercise(request, isbn):
    textbook = get_object_or_404(Textbook, isbn=isbn)

    if request.method == 'POST':
        page_number = request.POST['page_number']
        exercise_number = request.POST['exercise_number']
        solution = request.POST['solution']

        user = User.objects.get(username='dacksmdm')  # TODO: get the currently logged in user

        exercise = Exercise.objects.create(
            page_number=page_number,
            exercise_number=exercise_number,
            textbook=textbook,
            starter=user
        )

        solution_entry = Solution.objects.create(
            final_answer=solution,
            exercise=exercise,
            created_by=user
        )

        return redirect('textbooks:textbook_detail', isbn=textbook.isbn)  # TODO: redirect to the created topic page

    return render(request, 'textbooks/new_solution.html', {'textbook': textbook})


def page_detail(request, isbn, page_number):
    textbook = get_object_or_404(Textbook, isbn=isbn)
    exercises = Exercise.objects.filter(page_number=page_number)

    return render(request, 'textbooks/page_detail.html', {'textbook': textbook, 'exercises': exercises, 'page_number': page_number})

templates/index.html
{% extends "textbooks/base.html" %}

{% block content %}
<body class="body" style="background-color:#f6f6f6">
	<div>
		<h1>
			Welcome to Slader_Clone
		</h1>
		<ul>
			<li><a href="{% url 'textbooks:index' %}">Textbooks</a></li>
			<li><a href="{% url 'textbooks:about' %}">About me</li>
		</ul>
	</div>
</body>

{% endblock %}

textbooks/templates/textbooks/about.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Hello from the about me page!</h2>
  </body>
</html>

textbooks/templates/textbooks/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Textbooks{% endblock %}</title>
    {# <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">#}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/textbook-index.css' %}">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand" href="/">Slader</a>
      <a class="nav-link" href="/textbooks">Math Textbooks</a>
      <a class="nav-link" href="/science">Science Textbooks</a>
      <br/>
      <br/>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

    </nav>
  {% block content %}{% endblock%}

</html>

textbooks/templates/textbooks/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Harrison Kinsley</title>
	<meta charset="utf-8" />
</head>

<body class="body" style="background-color:#f6f6f6">
	<div>
	   {% block content %}
	   {% endblock %}
	</div>
</body>

</html>

textbooks/templates/textbooks/index.html
{% extends "textbooks/base.html" %}

{% block content %}
  <div class="container">
    <ol class="breadcrumb my-4">
      <li class="breadcrumb-item active">Textbooks</li>
    </ol>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th>ISBN</th>
          <th>Posts</th>
          <th>Topics</th>
          <th>Last Post</th>
        </tr>
      </thead>
      <tbody>
        {% for textbook in textbooks %}
          <tr>
            <td><img class="book-image" src="{{textbook.photo_url}}"></td>
            <td>
              <a href="{% url 'textbooks:textbook_detail' textbook.isbn %}">{{ textbook.title }}</a>
              <small class="text-muted d-block">{{ textbook.description }}</small>
            </td>
            <td><small>{{ textbook.isbn }}</small></td>
            <td class="align-middle">0</td>
            <td class="align-middle">0</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</body>
{% endblock %}

textbooks/templates/textbooks/new_solution.html
{% extends "textbooks/base.html" %}

{% block title %} Start a new Exercise {% endblock %}

{%block content%}
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">{{textbook.title}} - {{textbook.isbn}}</li>
        <br/>
        <li class="breadcrumb-item active"><em>{{textbook.author}}</em></li>
      </ol>

      <div class>
          <img class="book-image" src="{{textbook.photo_url}}">
          <br/>
          <br/>
      </div>

      <h2>New Exercise</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_subject">Page #</label>
          <input type="text" class="form-control" id="id_page_number" name="page_number">
        </div>
        <div class="form-group">
          <label for="id_subject">Exercise #</label>
          <input type="text" class="form-control" id="id_exercise_number" name="exercise_number">
        </div>
        <div class="form-group">
          <label for="id_message">Solution</label>
          <textarea class="form-control" id="id_solution" name="solution" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Post</button>
      </form>

</div> <!--End Container -->

  </body>
{% endblock %}

textbooks/templates/textbooks/page_detail.html
{% extends "textbooks/base.html" %}

{% block content %}

    <div class="container">

      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">{{textbook.title}} - {{textbook.isbn}}</li>
        <br/>
        <li class="breadcrumb-item active"><em>{{textbook.author}}</em></li>
      </ol>

      <div class>
          <img class="book-image" src="{{textbook.photo_url}}">
          <br/>
          <br/>
      </div>

      <div class="mb-4">
        <a href="{% url 'textbooks:new_exercise' textbook.pk %}" class="btn btn-primary">New exercise</a>
      </div>



      <h2>Current Page: <span style='color:green'>{{page_number}}</span></h2>

      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Exercise Number</th>
            <th>Starter</th>
            <th>Last Update</th>
          </tr>
        </thead>
        <tbody>


        {% for exercise in exercises.all|dictsort:'exercise_number' %}
          <tr>
            <td>{{ exercise.exercise_number }}</td>
            <td>{{ exercise.starter.username }}</td>
            <td>{{ exercise.last_updated }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>




    </div>
  </body>
{% endblock %}

textbooks/templates/textbooks/textbook_detail.html
{% extends "textbooks/base.html" %}

{% block content %}

    <div class="container">

      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">{{textbook.title}} - {{textbook.isbn}}</li>
        <br/>
        <li class="breadcrumb-item active"><em>{{textbook.author}}</em></li>
      </ol>

      <div class>
          <img class="book-image" src="{{textbook.photo_url}}">
          <br/>
          <br/>
      </div>

      <div class="mb-4">
        <a href="{% url 'textbooks:new_exercise' textbook.pk %}" class="btn btn-primary">New exercise</a>
      </div>




      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Page Number</th>
            <th>Exercise Number</th>
            <th>Starter</th>
            <th>Posts</th>
            <th>Last Update</th>
          </tr>
        </thead>
        <tbody>


        {% for exercise in textbook.exercises.all|dictsort:'page_number' %}
          <tr>
            <td>{{ exercise.page_number }}</td>
            <td>{{ exercise.exercise_number }}</td>
            <td>{{ exercise.starter }}</td>
            <td>0</td>
            <td>{{ exercise.last_updated }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>




    </div>
  </body>
{% endblock %}